# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Azure Python 3.5 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - name: Set up Python 3.5.10
        uses: actions/setup-python@v1 
        with:
          python-version: 3.5.10
      - name: Install dependencies
        run: |
          make install 
      - name: Lint
        run: |
          make lint 
      - name: Test
        run: |
          make test
